<a href="https://colab.research.google.com/github/leootimm/Modulo02_Projeto/blob/main/Modulo02_Projeto.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import pandas as pd

# leitura base
df=pd.read_csv('acidentes2025.csv', sep=';', encoding='latin1')

# cabeçalho
print(' :: ESTATÍSTICAS DE ACIDENTES EM ESTRADAS FEDERAIS')
print(' :: ANO 2025')
print()

# estatisticas iniciais
print(f"No ano de 2025 ocorreram {df.shape[0]:,} acidentes nas estradas federais brasileiras.".replace(',', '.'))

dia = df[df['fase_dia'].isin(['Pleno dia', 'Amanhecer'])].shape[0]
noite = df[df['fase_dia'].isin(['Plena Noite', 'Anoitecer'])].shape[0]
print('Destes,',f"{dia:,} foram durante o dia e {noite:,} a noite.".replace(',', '.'))

obitos = df[df['estado_fisico'] == 'Óbito']
obitos['fase_dia'].value_counts()
dia = obitos[obitos['fase_dia'].isin(['Pleno dia', 'Amanhecer'])].shape[0]
noite = obitos[obitos['fase_dia'].isin(['Plena Noite', 'Anoitecer'])].shape[0]
print(f"{noite:,} acidentes a noite e {dia:,} de dia tiveram óbito.".replace(',', '.'))

# demais consultas
print('_____________________________________')
print()

# criacao da coluna Faixa de Horário
horas = df['horario'].str[:2].astype(int)
limites = [-1, 5, 11, 17, 23]
rotulos = ['Madrugada', 'Manhã', 'Tarde', 'Noite']
df['faixa_horario'] = pd.cut(horas, bins=limites, labels=rotulos)
print('Em qual período do dia ocorreram mais acidentes?')
display((df['faixa_horario'].value_counts(normalize=True) * 100).map('{:.2f}%'.format).rename_axis(None).to_frame(''))

print('_____________________________________')
print()

print(f"Qual o tipo de pista?")
display(df['tipo_pista'].value_counts().rename_axis(None).to_frame(''))
print('_____________________________________')
print()

print('Principais causas de acidentes:')
display(df['causa_acidente'].value_counts().head(5).rename_axis(None).to_frame(''))
print('_____________________________________')
print()

meses_nome = {'01': 'Janeiro', '02': 'Fevereiro', '03': 'Março', '04': 'Abril', '05': 'Maio', '06': 'Junho',
              '07': 'Julho', '08': 'Agosto', '09': 'Setembro', '10': 'Outubro', '11': 'Novembro', '12': 'Dezembro'}
print('Em 2025, quais foram  os meses do ano com mais acidentes:')
display(df['data_inversa'].str[3:5].map(meses_nome).value_counts().head(3).rename_axis(None).to_frame(''))

print('_____________________________________')
print()

print('Qual o tipo de acidente possui mais vitimas fatais?')
fatais = df[df['classificacao_acidente'] == 'Com Vítimas Fatais']
tipo_mais_fatal = fatais['tipo_acidente'].value_counts().idxmax()
qtd_fatais = fatais['tipo_acidente'].value_counts().max()

print(f"- {tipo_mais_fatal} com {qtd_fatais} ocorrências.")

print('_____________________________________')
print()

print('Quais as 3 estradas federais possuem mais acidentes:')
display(df["br"].value_counts().head(3).to_frame(name='').rename_axis("BR"))

print('_____________________________________')
print()

print('Quais são os 10 municípios cujos trechos de rodovias federais registram mais acidentes?')
top_10_cidades = df[['municipio']].value_counts().head(10)
display(top_10_cidades.rename_axis(None).to_frame(''))
print('_____________________________________')
print()


print('Percentual de informações em branco em comparação ao total de registros:')
nulos = (df.isnull().sum() / df.shape[0] * 100).round(2)
display(nulos[nulos > 0].map('{:.2f}%'.format).rename_axis(None).to_frame(''))

 :: ESTATÍSTICAS DE ACIDENTES EM ESTRADAS FEDERAIS
 :: ANO 2025

No ano de 2025 ocorreram 194.629 acidentes nas estradas federais brasileiras.
Destes, 119.829 foram durante o dia e 74.800 a noite.
3.180 acidentes a noite e 2.863 de dia tiveram óbito.
_____________________________________

Em qual período do dia ocorreram mais acidentes?

Tarde      31.78%
Manhã      28.93%
Noite      27.52%
Madrugada  11.77%

_____________________________________

Qual o tipo de pista?

Simples   100098
Dupla      77245
Múltipla   17286

_____________________________________

Principais causas de acidentes:

Reação tardia ou ineficiente do condutor            28518
Ausência de reação do condutor                      27925
Acessar a via sem observar a presença dos outro...  20425
Condutor deixou de manter distância do veículo ...  14056
Manobra de mudança de faixa                         11550

_____________________________________

Em 2025, quais foram  os meses do ano com mais acidentes:

Dezembro  18611
Julho     17251
Agosto    16607

_____________________________________

Qual o tipo de acidente possui mais vitimas fatais?
- Colisão frontal com 6050 ocorrências.
_____________________________________

Quais as 3 estradas federais possuem mais acidentes:

BR
101  32151
116  28969
381   9186

_____________________________________

Quais são os 10 municípios cujos trechos de rodovias federais registram mais acidentes?

BRASILIA         2524
DUQUE DE CAXIAS  1984
SAO JOSE         1786
CURITIBA         1771
GUARULHOS        1705
BETIM            1687
RECIFE           1499
PALHOCA          1420
SERRA            1386
JOAO PESSOA      1249

_____________________________________

Percentual de informações em branco em comparação ao total de registros:

tipo_veiculo    3.26%
tipo_envolvido  8.81%
estado_fisico   8.81%
sexo            8.81%